import { useContext } from "react";
import { ProjectContext } from "../context/ProjectContext";

export function useProject() {
  const {
    workspace,
    setWorkspace,
    project,
    setProject,
    layerManager,
    setLayerManager,
    editDocument,
    setEditDocument,
    undoRedoManager,
    setUndoRedoManager,
    loading,
    setLoading,
    trigger,
    setTrigger,
    landing,
    setLanding,
    editMode,
    setEditMode,
    isLoadingBar,
    setIsLoadingBar,
    loadingProgress,
    setLoadingProgress,
    loadingTask,
    setLoadingTask,
    loadingProgressText,
    setLoadingProgressText,
    activeDocumentId,
    activeDocument,
    createBlankDocument,
    openImageFile,
    openProjectFile,
    activateDocument,
    reorderDocuments,
    closeDocument,
    cycleDocuments,
    markDocumentSaved,
    updateActiveCanvasView,
  } = useContext(ProjectContext);

  return {
    workspace,
    setWorkspace,
    project,
    setProject,
    layerManager,
    setLayerManager,
    editDocument,
    setEditDocument,
    undoRedoManager,
    setUndoRedoManager,
    loading,
    setLoading,
    trigger,
    landing,
    setLanding,
    setTrigger,
    editMode,
    setEditMode,
    isLoadingBar,
    setIsLoadingBar,
    loadingProgress,
    setLoadingProgress,
    loadingTask,
    setLoadingTask,
    loadingProgressText,
    setLoadingProgressText,
    activeDocumentId,
    activeDocument,
    createBlankDocument,
    openImageFile,
    openProjectFile,
    activateDocument,
    reorderDocuments,
    closeDocument,
    cycleDocuments,
    markDocumentSaved,
    updateActiveCanvasView,
  };
}
